name: Deploy
on:
  push:
    branches:
      - staging

jobs:
  DeployMCGJ:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send Pull Command
      id: pull-cmd
      uses: satak/webrequest-action@master
      with:
        url: ${{secrets.CONSOLE_URI_STAGING}}
        method: POST
        payload: ${{secrets.PULL_CMD_STAGING}}
        headers: ${{secrets.AUTH_HEADER_STAGING}}
    - name: Trigger Reload
      id: reload
      uses: satak/webrequest-action@master
      with:
        url: ${{secrets.RELOAD_URI_STAGING}}
        method: POST
        headers: ${{secrets.AUTH_HEADER_STAGING}}
