name: Test Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - sarabee-test

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - name: Test Request
      id: test-request
      uses: CamiloGarciaLaRotta/watermelon-http-client@v1.4
      with:
        # a super fun test URL
        url: https://www.recurse.com/
    - name: Print the response status
      run: echo ${{ steps.test-request.outputs.status }}
      shell: bash
    - name: Print the response headers
      run: echo ${{ steps.test-request.outputs.headers }}
      shell: bash
    - name: Print the response payload
      run: echo ${{ steps.test-request.outputs.response }}
      shell: bash
